services:
  postgres:
    image: postgres:15.2-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    image: ibayazit/nestjs-wallet-app:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
